# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackernews < Formula
  desc "SlackerNews CLI for terminal-based link browsing"
  homepage "https://slackernews.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "8d66f928bfabbcd224f6c6138899ed86c6309d62d4939c64a7a8210a373e55b5"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "1f2d6644df9df3fe3e62fa5e3b7db2a0da2106f645d36cc6d16ec84ee67fe44c"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "054c263c28808afcf99a46970802ab10e511f243a21d69117d2c056d2b10feac"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "39507d4d61f0521e0540bbc0b2c1dea0812f3540afb1a069e89f2d76c7978943"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  test do
    system "#{bin}/slackernews", "--version"
  end
end
