# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackernews < Formula
  desc "SlackerNews CLI for terminal-based link browsing"
  homepage "https://slackernews.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "bdd020a4795e80bc7dd574e50682886eca9acf2eade0887f22e0fc47d360a623"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "396c450acf2096a8ad7328a8fa55126b2935668101fbf5f7b5c9b4c85eb33952"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cd230afee0476060d3176da1eec6f0e866a7ca1d6bbb3b7733a6294eb1219610"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "6befecc8491ba135cdf89ce6aa35e38970be138745b060f58f8803a69341741d"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  test do
    system "#{bin}/slackernews", "--version"
  end
end
