# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackernews < Formula
  desc "SlackerNews CLI for terminal-based link browsing"
  homepage "https://slackernews.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "afefddaaaa58ec2ef04191b4c0f84233a1311fd7ce66078c925caa22642ac35d"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "2e3bebb516e3597c28e640eec0686b7ec6528dd1dd6280b8102245db9ebcd50e"

      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7dcc533ec606a3d820d6399fedf56a78a58b2e230c2dc595c5b8786acaba4e38"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slackernews/cli/releases/download/v0.1.0/cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "3243a23067d2640e6873c4aa23c804d3d1aee7cc62668c38a8a6efd436987aef"
      define_method(:install) do
        bin.install "slackernews"
      end
    end
  end

  test do
    system "#{bin}/slackernews", "--version"
  end
end
